/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import UranusModel from '../assets/3d/Uranus.glb'

const Uranus=(props) =>{
  const { nodes, materials } = useGLTF(UranusModel)
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Uranus.geometry}
        material={materials['Default OBJ.001']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

export default Uranus;
